#!/bin/bash

cd $HOME/bes/DDPIPI/v0.2/python
# data (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_before.root 4.600 before STDDmiss_signal
# data: sidebandlow (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*STDDmiss_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_STDDmiss_sidebandlow_before.root 4.358 before STDDmiss_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*STDDmiss_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_STDDmiss_sidebandlow_before.root 4.416 before STDDmiss_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*STDDmiss_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_STDDmiss_sidebandlow_before.root 4.600 before STDDmiss_sidebandlow
# data: sidebandlow (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*STDDmiss_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_STDDmiss_sidebandup_before.root 4.358 before STDDmiss_sidebandup
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*STDDmiss_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_STDDmiss_sidebandup_before.root 4.416 before STDDmiss_sidebandup
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*STDDmiss_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_STDDmiss_sidebandup_before.root 4.600 before STDDmiss_sidebandup
# data (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*raw_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*raw_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*raw_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_before.root 4.600 before raw_signal
# data: sidebandlow (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*raw_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_sidebandlow_before.root 4.358 before raw_sidebandlowmkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*raw_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_sidebandlow_before.root 4.416 before raw_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*raw_sidebandlow_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_sidebandlow.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_sidebandlow_before.root 4.600 before raw_sidebandlow
# data: sidebandlow (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*raw_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_sidebandup_before.root 4.358 before raw_sidebandup
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*raw_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_sidebandup_before.root 4.416 before raw_sidebandup
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*raw_sidebandup_before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_sidebandup.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_sidebandup_before.root 4.600 before raw_sidebandup
# signal MC: X_3842
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/sigMC_X_3842_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/sigMC_X_3842_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/sigMC_X_3842_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/sigMC_X_3842_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/sigMC_X_3842_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/sigMC_X_3842_4600_before.root 4.600 before STDDmiss_signal
# signal MC: D1_2420 (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/sigMC_D1_2420_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/sigMC_D1_2420_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/sigMC_D1_2420_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/sigMC_D1_2420_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/sigMC_D1_2420_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/sigMC_D1_2420_4600_before.root 4.600 before STDDmiss_signal
# signal MC: D1_2420 (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/sigMC_D1_2420_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/sigMC_D1_2420_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/sigMC_D1_2420_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/sigMC_D1_2420_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/sigMC_D1_2420_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/sigMC_D1_2420_4600_raw_before.root 4.600 before raw_signal
# signal MC: psipp (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/sigMC_psipp_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/sigMC_psipp_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/sigMC_psipp_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/sigMC_psipp_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/sigMC_psipp_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/sigMC_psipp_4600_before.root 4.600 before STDDmiss_signal
# signal MC: psipp (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/sigMC_psipp_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/sigMC_psipp_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/sigMC_psipp_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/sigMC_psipp_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/sigMC_psipp_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/sigMC_psipp_4600_raw_before.root 4.600 before raw_signal
# signal MC: D2_2460
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4360/sigMC_D2_2460_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4360/sigMC_D2_2460_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4420/sigMC_D2_2460_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4420/sigMC_D2_2460_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4600/sigMC_D2_2460_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4600/sigMC_D2_2460_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: DD (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/incMC_DD_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/incMC_DD_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/incMC_DD_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/incMC_DD_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/incMC_DD_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/incMC_DD_4600_before.root 4.600 before STDDmiss_signal
# signal MC: DD (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/incMC_DD_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/incMC_DD_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/incMC_DD_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/incMC_DD_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/incMC_DD_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/incMC_DD_4600_raw_before.root 4.600 before raw_signal
# inclusive MC: qq (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/incMC_qq_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/incMC_qq_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/incMC_qq_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/incMC_qq_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/incMC_qq_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/incMC_qq_4600_before.root 4.600 before STDDmiss_signal
# signal MC: qq (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/incMC_qq_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/incMC_qq_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/incMC_qq_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/incMC_qq_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/incMC_qq_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/incMC_qq_4600_raw_before.root 4.600 before raw_signal
# inclusive MC: bhabha
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4360/incMC_bhabha_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4360/incMC_bhabha_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4420/incMC_bhabha_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4420/incMC_bhabha_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4600/incMC_bhabha_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4600/incMC_bhabha_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: digamma
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4360/incMC_digamma_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4360/incMC_digamma_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4420/incMC_digamma_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4420/incMC_digamma_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4600/incMC_digamma_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/digamma/4600/incMC_digamma_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: dimu
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4360/incMC_dimu_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4360/incMC_dimu_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4420/incMC_dimu_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4420/incMC_dimu_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4600/incMC_dimu_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/dimu/4600/incMC_dimu_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: ditau
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4360/incMC_ditau_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4360/incMC_ditau_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4420/incMC_ditau_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4420/incMC_ditau_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4600/incMC_ditau_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ditau/4600/incMC_ditau_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: gammaXYZ
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/gammaXYZ/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/gammaXYZ/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/gammaXYZ/4360/incMC_gammaXYZ_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/gammaXYZ/4360/incMC_gammaXYZ_4360_before.root 4.358 before STDDmiss_signal
# inclusive MC: hadrons
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/incMC_hadrons_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/incMC_hadrons_4360_before.root 4.358 before STDDmiss_signal
# inclusive MC: ISR
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ISR/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ISR/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ISR/4360/incMC_ISR_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/ISR/4360/incMC_ISR_4360_before.root 4.358 before STDDmiss_signal
# inclusive MC: LL
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/incMC_LL_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/incMC_LL_4600_before.root 4.600 before STDDmiss_signal
# inclusive MC: twogamma
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4360/incMC_twogamma_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4360/incMC_twogamma_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4600/incMC_twogamma_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4600/incMC_twogamma_4600_before.root 4.600 before STDDmiss_signal
# background MC: DDPIPI
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4360/bkgMC_D_D_PI_PI_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4360/bkgMC_D_D_PI_PI_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4420/bkgMC_D_D_PI_PI_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4420/bkgMC_D_D_PI_PI_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4600/bkgMC_D_D_PI_PI_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4600/bkgMC_D_D_PI_PI_4600_before.root 4.600 before STDDmiss_signal
# signal MC: D0_2300 (STDDmiss)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/sigMC_D0_2300_4360_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/sigMC_D0_2300_4360_before.root 4.358 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/sigMC_D0_2300_4420_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/sigMC_D0_2300_4420_before.root 4.416 before STDDmiss_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/sigMC_D0_2300_4600_signal.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/sigMC_D0_2300_4600_before.root 4.600 before STDDmiss_signal
# signal MC: D0_2300 (raw)
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/sigMC_D0_2300_4360_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4360/sigMC_D0_2300_4360_raw_before.root 4.358 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/sigMC_D0_2300_4420_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4420/sigMC_D0_2300_4420_raw_before.root 4.416 before raw_signal
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/*before*.root
python apply_cuts.py /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/sigMC_D0_2300_4600_raw.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/D0_2300/4600/sigMC_D0_2300_4600_raw_before.root 4.600 before raw_signal
