#!/bin/bash

cd $HOME/bes/DDPIPI/v0.1/python
# data
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/data/4360
rm -rf /besfs/users/$USER/DDPIPI/v0.1/data/4360/data_4360_control.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/data/4360/data_4360.root /besfs/users/$USER/DDPIPI/v0.1/data/4360/data_4360_control.root 4.358
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/data/4420
rm -rf /besfs/users/$USER/DDPIPI/v0.1/data/4420/data_4420_control.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/data/4420/data_4420.root /besfs/users/$USER/DDPIPI/v0.1/data/4420/data_4420_control.root 4.415
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/data/4600
rm -rf /besfs/users/$USER/DDPIPI/v0.1/data/4600/data_4600_control.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/data/4600/data_4600.root /besfs/users/$USER/DDPIPI/v0.1/data/4600/data_4600_control.root 4.600
# inclusive MC: DD
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4360
rm -rf /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4360/controlMC_DD_4360.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/controlMC/DD/4360/rootfile/controlMC_DD_4360.root /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4360/controlMC_DD_4360.root 4.358
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4420
rm -rf /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4420/controlMC_DD_4420.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/controlMC/DD/4420/rootfile/controlMC_DD_4420.root /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4420/controlMC_DD_4420.root 4.415
mkdir -p /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4600
rm -rf /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4600/controlMC_DD_4600.root
python sel_control_events.py /scratchfs/bes/$USER/bes/DDPIPI/v0.1/controlMC/DD/4600/rootfile/controlMC_DD_4600.root /besfs/users/$USER/DDPIPI/v0.1/controlMC/DD/4600/controlMC_DD_4600.root 4.600
