#!/bin/bash

cd $HOME/bes/DDPIPI/v0.2/python
# inclusive MC: hadrons
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/rootfile/incMC_hadrons_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/incMC_hadrons_4360_topo.root 4.358 allTruth 
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/rootfile/incMC_hadrons_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/incMC_hadrons_4420_topo.root 4.415 allTruth
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/rootfile/incMC_hadrons_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/incMC_hadrons_4600_topo.root 4.600 allTruth
