#!/bin/bash

cd $HOME/bes/DDPIPI/v0.2/python
# inclusive MC: hadrons
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/rootfile/incMC_hadrons_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/incMC_hadrons_4360_topolow.root 4.358 sidebandlow_truth
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/rootfile/incMC_hadrons_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/incMC_hadrons_4360_topoup.root 4.358 sidebandup_truth
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/rootfile/incMC_hadrons_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/incMC_hadrons_4420_topolow.root 4.415 sidebandlow_truth
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/rootfile/incMC_hadrons_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4420/incMC_hadrons_4420_topoup.root 4.415 sidebandup_truth
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/*topo*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/rootfile/incMC_hadrons_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/incMC_hadrons_4600_topolow.root 4.600 sidebandlow_truth
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/rootfile/incMC_hadrons_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4600/incMC_hadrons_4600_topoup.root 4.600 sidebandup_truth
