#!/bin/bash

cp -rf $HOME/bes/DDPIPI/v0.1/simultanous/signalshape/4360/*.cxx .

root -l -q get_signal_hist_4360.cxx
sleep 300
root -l -q get_sideband_hist_4360.cxx
sleep 300
root -l -q get_signal_shape_4360.cxx
