#!/bin/bash

cd $HOME/bes/DDPIPI/v0.2/python
# data
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4360/data_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_sidebandlow.root 4.358 STDDmiss_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4420/data_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_sidebandlow.root 4.416 STDDmiss_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4600/data_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_sidebandlow.root 4.600 STDDmiss_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*raw_sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4360/data_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_raw_sidebandlow.root 4.358 raw_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*raw_sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4420/data_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_raw_sidebandlow.root 4.416 raw_sidebandlow
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*raw_sidebandlow*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4600/data_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_raw_sidebandlow.root 4.600 raw_sidebandlow
