#!/bin/bash

cd $HOME/bes/DDPIPI/v0.2/python
# data
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4360/data_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4360/data_4360_selected.root 4.358
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4420/data_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4420/data_4420_selected.root 4.415
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4600/data_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/data/4600/data_4600_selected.root 4.600
# signal MC: X_3842
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/rootfile/sigMC_X_3842_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/sigMC_X_3842_4360_selected.root 4.358
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/rootfile/sigMC_X_3842_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/sigMC_X_3842_4420_selected.root 4.415
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/rootfile/sigMC_X_3842_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/sigMC_X_3842_4600_selected.root 4.600
# inclusive MC: DD
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/rootfile/incMC_DD_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/incMC_DD_4360_selected.root 4.358
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/rootfile/incMC_DD_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/incMC_DD_4420_selected.root 4.415
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/rootfile/incMC_DD_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/incMC_DD_4600_selected.root 4.600
# inclusive MC: qq
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/rootfile/incMC_qq_4360.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/incMC_qq_4360_selected.root 4.358
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/rootfile/incMC_qq_4420.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/incMC_qq_4420_selected.root 4.415
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/rootfile/incMC_qq_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/incMC_qq_4600_selected.root 4.600
# inclusive MC: LL
mkdir -p /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600
rm -rf /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/*.root
python get_info.py /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/rootfile/incMC_LL_4600.root /besfs/users/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/incMC_LL_4600_selected.root 4.600
