#!/bin/bash

cp -rf $HOME/bes/DDPIPI/v0.1/simultanous/signalshape/4600/*.cxx .

root -l -q get_signal_hist_4600.cxx
sleep 300
root -l -q get_sideband_hist_4600.cxx
sleep 300
root -l -q get_signal_shape_4600.cxx
