#!/bin/bash

cp -rf $HOME/bes/DDPIPI/v0.1/simultanous/signalshape/4360/*.cxx .

root -b<<EOF
.L get_signal_hist_4360.cxx
.x get_signal_hist_4360.cxx++
.q
EOF

sleep 300

root -b<<EOF
.L get_sideband_hist_4360.cxx
.x get_sideband_hist_4360.cxx++
.q
EOF

sleep 300

root -b<<EOF
.L get_signal_shape_4360.cxx
.x get_signal_shape_4360.cxx++
.q
EOF
