#!/bin/bash

# data
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4360
rm -rf data_4360.root
hadd data_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4420
rm -rf data_4420.root
hadd data_4420_temp1.root data31*.root
hadd data_4420_temp2.root data36*.root
hadd data_4420_temp3.root data37*.root
hadd data_4420_temp4.root data38*.root
hadd data_4420.root data_4420_temp*.root
rm -rf data_4420_temp*.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/data/4600
rm -rf data_4600.root
hadd data_4600.root *.root
# signal MC: X_3842
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4360/rootfile
rm -rf sigMC_X_3842_4360.root
hadd sigMC_X_3842_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4420/rootfile
rm -rf sigMC_X_3842_4420.root
hadd sigMC_X_3842_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/X_3842/4600/rootfile
rm -rf sigMC_X_3842_4600.root
hadd sigMC_X_3842_4600.root *.root
# signal MC: D1(2420)
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4360/rootfile
rm -rf sigMC_D1_2420_4360.root
hadd sigMC_D1_2420_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4420/rootfile
rm -rf sigMC_D1_2420_4420.root
hadd sigMC_D1_2420_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D1_2420/4600/rootfile
rm -rf sigMC_D1_2420_4600.root
hadd sigMC_D1_2420_4600.root *.root
# signal MC: psi(3770)
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4360/rootfile
rm -rf sigMC_psipp_4360.root
hadd sigMC_psipp_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4420/rootfile
rm -rf sigMC_psipp_4420.root
hadd sigMC_psipp_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/psipp/4600/rootfile
rm -rf sigMC_psipp_4600.root
hadd sigMC_psipp_4600.root *.root
# signal MC: D2(2460)
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4360/rootfile
rm -rf sigMC_D2_2460_4360.root
hadd sigMC_D2_2460_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4420/rootfile
rm -rf sigMC_D2_2460_4420.root
hadd sigMC_D2_2460_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/sigMC/D2_2460/4600/rootfile
rm -rf sigMC_D2_2460_4600.root
hadd sigMC_D2_2460_4600.root *.root
# inclusive MC: DD
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4360/rootfile
rm -rf incMC_DD_4360.root
hadd incMC_DD_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4420/rootfile
rm -rf incMC_DD_4420.root
hadd incMC_DD_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/DD/4600/rootfile
rm -rf incMC_DD_4600.root
hadd incMC_DD_4600.root *.root
# inclusive MC: qq
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4360/rootfile
rm -rf incMC_qq_4360.root
hadd incMC_qq_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4420/rootfile
rm -rf incMC_qq_4420.root
hadd incMC_qq_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/qq/4600/rootfile
rm -rf incMC_qq_4600.root
hadd incMC_qq_4600.root *.root
# inclusive MC: bhabha
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4360/rootfile
rm -rf incMC_bhabha_4360.root
hadd incMC_bhabha_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4420/rootfile
rm -rf incMC_bhabha_4420.root
hadd incMC_bhabha_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/bhabha/4600/rootfile
rm -rf incMC_bhabha_4600.root
hadd incMC_bhabha_4600.root *.root
# inclusive MC: digamma
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/digamma/4360/rootfile
rm -rf incMC_digamma_4360.root
hadd incMC_digamma_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/digamma/4420/rootfile
rm -rf incMC_digamma_4420.root
hadd incMC_digamma_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/digamma/4600/rootfile
rm -rf incMC_digamma_4600.root
hadd incMC_digamma_4600.root *.root
# inclusive MC: dimu
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/dimu/4360/rootfile
rm -rf incMC_dimu_4360.root
hadd incMC_dimu_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/dimu/4420/rootfile
rm -rf incMC_dimu_4420.root
hadd incMC_dimu_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/dimu/4600/rootfile
rm -rf incMC_dimu_4600.root
hadd incMC_dimu_4600.root *.root
# inclusive MC: ditau
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/ditau/4360/rootfile
rm -rf incMC_ditau_4360.root
hadd incMC_ditau_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/ditau/4420/rootfile
rm -rf incMC_ditau_4420.root
hadd incMC_ditau_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/ditau/4600/rootfile
rm -rf incMC_ditau_4600.root
hadd incMC_ditau_4600.root *.root
# inclusive MC: gammaXYZ
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/gammaXYZ/4360/rootfile
rm -rf incMC_gammaXYZ_4360.root
hadd incMC_gammaXYZ_4360.root *.root
# inclusive MC: hadrons
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/hadrons/4360/rootfile
rm -rf incMC_hadrons_4360.root
hadd incMC_hadrons_4360.root *.root
# inclusive MC: ISR
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/ISR/4360/rootfile
rm -rf incMC_ISR_4360.root
hadd incMC_ISR_4360.root *.root
# inclusive MC: LL
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/LL/4600/rootfile
rm -rf incMC_LL_4600.root
hadd incMC_LL_4600.root *.root
# inclusive MC: twogamma
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4360/rootfile
rm -rf incMC_twogamma_4360.root
hadd incMC_twogamma_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/incMC/twogamma/4600/rootfile
rm -rf incMC_twogamma_4600.root
hadd incMC_twogamma_4600.root *.root
# background MC: DDPIPI
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4360/rootfile
rm -rf bkgMC_D_D_PI_PI_4360.root
hadd bkgMC_D_D_PI_PI_4360.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4420/rootfile
rm -rf bkgMC_D_D_PI_PI_4420.root
hadd bkgMC_D_D_PI_PI_4420.root *.root
cd /scratchfs/bes/$USER/bes/DDPIPI/v0.2/bkgMC/DDPIPI/4600/rootfile
rm -rf bkgMC_D_D_PI_PI_4600.root
hadd bkgMC_D_D_PI_PI_4600.root *.root
